services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: app
    container_name: go-api-gateway
    restart: unless-stopped
    env_file: .env
    ports:
      - "$APP_PORT:$APP_PORT"
    networks:
      - proxy

networks:
  proxy:
    external: true
