services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: app
    container_name: go-api-gateway
    restart: unless-stopped
    env_file: .env
    ports:
      - "${API_PORT:-8080}:${API_PORT:-8080}"
    networks:
      - public

networks:
  public:
    external: true
